version: "3"
services:
  postgres:
    build:
      context: db
      dockerfile: Dockerfile
    image: "db"
    container_name: ${DB_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: ${DB_DATA}
    ports:
      - "5432:5432"
    restart: unless-stopped
  nginx:
    depends_on:
      - client
      - api
      - postgres
    restart: always
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  api:
    image: "server"
    depends_on:
      - postgres
    build:
      context: server
      dockerfile: Dockerfile
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOSTNAME: ${DB_HOSTNAME}
    ports:
      - "3000:3000"
  client:
    image: "client"
    stdin_open: true
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
